Repository OCA/payroll, pull requests merged in 2022-08, with the labels that each got.

#47 [14.0] [IMP] payroll: payslip refactoring
  payroll/models/hr_payslip.py
  payroll/models/hr_payslip_run.py
  payroll/views/hr_payslip_run_views.xml
  payroll/views/hr_payslip_views.xml
  payroll/wizard/hr_payroll_payslips_by_employees.py
Labels: approved, bot is merging ⏳

#50 [IMP] payroll: allow the use of positive values in leave days/hours c…
  payroll/models/hr_payslip.py
  payroll/models/res_config_settings.py
  payroll/tests/__init__.py
  payroll/tests/common.py
  payroll/tests/test_hr_payslip_worked_days.py
  payroll/views/res_config_settings_views.xml
Labels: approved, bot is merging ⏳

#45 [14.0] [IMP] payroll: Remove contract_advantage_template model and new module
  payroll/__manifest__.py
  payroll/models/__init__.py
  payroll/security/ir.model.access.csv
  payroll_contract_advantages/README.rst
  payroll_contract_advantages/__init__.py
  payroll_contract_advantages/__manifest__.py
  payroll_contract_advantages/models/__init__.py
  payroll_contract_advantages/models/hr_contract.py
  payroll_contract_advantages/models/hr_contract_advantage.py
  payroll_contract_advantages/models/hr_contract_advantage_template.py
  payroll_contract_advantages/models/hr_payslip.py
  payroll_contract_advantages/readme/CONTRIBUTORS.rst
  payroll_contract_advantages/readme/DESCRIPTION.rst
  payroll_contract_advantages/readme/USAGE.rst
  payroll_contract_advantages/security/ir.model.access.csv
  payroll_contract_advantages/views/hr_contract_advantage_views.xml
  payroll_contract_advantages/views/hr_contract_views.xml
  setup/payroll_contract_advantages/odoo/addons/payroll_contract_advantages
  setup/payroll_contract_advantages/setup.py
Labels: bot is merging ⏳

#55 [14.0][FIX] payroll_account: log a warning if no move lines are generated for the payslip
  payroll_account/models/hr_payroll_account.py
  payroll_account/tests/test_payroll_account.py
Labels: bot is merging ⏳

#56 [FIX] payroll: Fix Refactored _compute_name to contemplate more than …
  payroll/models/hr_payslip.py
Labels: bot is merging ⏳

#57 [FIX] payroll: use a custom working calendar so tests don't fail on weekends
  payroll/tests/common.py
  payroll/tests/test_hr_payslip_worked_days.py
Labels: bot is merging ⏳

#53 [14.0][IMP] payroll: send email with payslip, fix payslip form view, better payslip line views
  payroll/__manifest__.py
  payroll/models/hr_payslip_line.py
  payroll/views/hr_payslip_line_views.xml
  payroll/views/hr_payslip_views.xml
  payroll/wizard/hr_payroll_send_email.xml
Labels: bot is merging ⏳

#60 [IMP] payroll: Improve views, add child functionalities, allow compute of name
  payroll/models/hr_payslip.py
  payroll/models/hr_payslip_line.py
  payroll/models/hr_salary_rule.py
  payroll/tests/common.py
  payroll/tests/test_hr_salary_rule.py
  payroll/tests/test_payslip_flow.py
  payroll/views/hr_payslip_line_views.xml
  payroll/views/hr_payslip_views.xml
  payroll/views/hr_salary_rule_views.xml
Labels: ready to merge, approved, bot is merging ⏳
