Repository OCA/payroll, pull requests merged in 2024-03, with the labels that each got.

#136 [16.0][ADD] hr_payroll_document: New module hr_payroll_document
  hr_payroll_document/README.rst
  hr_payroll_document/__init__.py
  hr_payroll_document/__manifest__.py
  hr_payroll_document/data/email_payroll_employee.xml
  hr_payroll_document/i18n/ca_ES.po
  hr_payroll_document/i18n/es.po
  hr_payroll_document/models/__init__.py
  hr_payroll_document/models/hr_employee.py
  hr_payroll_document/models/ir_attachment.py
  hr_payroll_document/models/ir_attachment_payroll_custom.py
  hr_payroll_document/readme/CONTRIBUTORS.rst
  hr_payroll_document/readme/DESCRIPTION.rst
  hr_payroll_document/security/ir.model.access.csv
  hr_payroll_document/static/description/index.html
  hr_payroll_document/tests/__init__.py
  hr_payroll_document/tests/common.py
  hr_payroll_document/tests/test.docx
  hr_payroll_document/tests/test.pdf
  hr_payroll_document/tests/test_hr_payroll_document.py
  hr_payroll_document/wizard/__init__.py
  hr_payroll_document/wizard/payroll_management_wizard.py
  hr_payroll_document/wizard/payroll_management_wizard.xml
  requirements.txt
  setup/hr_payroll_document/odoo/addons/hr_payroll_document
  setup/hr_payroll_document/setup.py
Labels: ready to merge, approved, bot is merging ⏳

#147 [15.0][IMP] update copier from template
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
  payroll/views/report_contributionregister.xml
  payroll/views/report_payslipdetails.xml
Labels: bot is merging ⏳

#148 [14.0][FIX] hr_payroll_period: incorrect migration script.
  hr_payroll_period/migrations/14.0.1.0.0/pre-migration.py
Labels: approved, bot is merging ⏳

#146 [15.0][IMP] payroll_account: allow other modules to influence the values of the journal items
  payroll_account/models/hr_payroll_account.py
Labels: approved, bot is merging ⏳
