Repository OCA/payroll, pull requests merged in 2025-01, with the labels that each got.

#181 [IMP] payroll: UX improvements, better error messages
  payroll/models/hr_salary_rule.py
  payroll/views/hr_payslip_views.xml
  payroll/views/hr_salary_rule_views.xml
Labels: needs review, bot is merging ⏳

#180 [17.0][FW] payroll: ported 111, 117, 119, 151
  payroll/README.rst
  payroll/__manifest__.py
  payroll/models/base_browsable.py
  payroll/models/hr_payslip.py
  payroll/models/hr_salary_rule.py
  payroll/static/description/index.html
  payroll/tests/test_hr_salary_rule.py
  payroll/views/hr_leave_type.xml
  payroll/views/hr_payslip_views.xml
Labels: bot is merging ⏳

#179 [16.0][MIG] hr_payroll_period
  hr_payroll_period/README.rst
  hr_payroll_period/__init__.py
  hr_payroll_period/__manifest__.py
  hr_payroll_period/data/date_range_type.xml
  hr_payroll_period/data/ir_cron.xml
  hr_payroll_period/data/ir_sequence_data.xml
  hr_payroll_period/i18n/de.po
  hr_payroll_period/i18n/es.po
  hr_payroll_period/i18n/es_AR.po
  hr_payroll_period/i18n/fr.po
  hr_payroll_period/i18n/hr_payroll_period.pot
  hr_payroll_period/i18n/hr_period.pot
  hr_payroll_period/models/__init__.py
  hr_payroll_period/models/date_range_type.py
  hr_payroll_period/models/hr_contract.py
  hr_payroll_period/models/hr_employee.py
  hr_payroll_period/models/hr_fiscal_year.py
  hr_payroll_period/models/hr_payslip.py
  hr_payroll_period/models/hr_payslip_employees.py
  hr_payroll_period/models/hr_payslip_run.py
  hr_payroll_period/models/hr_period.py
  hr_payroll_period/readme/CONFIGURE.rst
  hr_payroll_period/readme/CONTRIBUTORS.rst
  hr_payroll_period/readme/DESCRIPTION.rst
  hr_payroll_period/readme/INSTALL.rst
  hr_payroll_period/readme/ROADMAP.rst
  hr_payroll_period/readme/USAGE.rst
  hr_payroll_period/security/hr_period_security.xml
  hr_payroll_period/security/ir.model.access.csv
  hr_payroll_period/static/description/icon.png
  hr_payroll_period/static/description/index.html
  hr_payroll_period/tests/__init__.py
  hr_payroll_period/tests/test_hr_fiscalyear.py
  hr_payroll_period/tests/test_payslip.py
  hr_payroll_period/views/date_range_type_view.xml
  hr_payroll_period/views/hr_fiscalyear_view.xml
  hr_payroll_period/views/hr_payslip_employee_view.xml
  hr_payroll_period/views/hr_payslip_run_view.xml
  hr_payroll_period/views/hr_payslip_view.xml
  hr_payroll_period/views/hr_period_view.xml
  hr_payroll_period/views/menus.xml
  setup/hr_payroll_period/odoo/addons/hr_payroll_period
  setup/hr_payroll_period/setup.py
Labels: approved, bot is merging ⏳

#186 [16.0][FW] payroll: salary rule code: payslip.line_sum_where() (port of #117)
  payroll/__manifest__.py
  payroll/models/hr_payslip.py
  payroll/readme/CONTRIBUTORS.rst
  payroll/tests/test_hr_salary_rule.py
Labels: bot is merging ⏳
